// Code generated by go-swagger; DO NOT EDIT.

package key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PlayHandlerFunc turns a function with the right signature into a play handler
type PlayHandlerFunc func(PlayParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PlayHandlerFunc) Handle(params PlayParams) middleware.Responder {
	return fn(params)
}

// PlayHandler interface for that can handle valid play params
type PlayHandler interface {
	Handle(PlayParams) middleware.Responder
}

// NewPlay creates a new http.Handler for the play operation
func NewPlay(ctx *middleware.Context, handler PlayHandler) *Play {
	return &Play{Context: ctx, Handler: handler}
}

/*Play swagger:route GET /{speakerName}/play key play

starts playing

*/
type Play struct {
	Context *middleware.Context
	Handler PlayHandler
}

func (o *Play) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPlayParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
