// Code generated by go-swagger; DO NOT EDIT.

package key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PowerOffHandlerFunc turns a function with the right signature into a power off handler
type PowerOffHandlerFunc func(PowerOffParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PowerOffHandlerFunc) Handle(params PowerOffParams) middleware.Responder {
	return fn(params)
}

// PowerOffHandler interface for that can handle valid power off params
type PowerOffHandler interface {
	Handle(PowerOffParams) middleware.Responder
}

// NewPowerOff creates a new http.Handler for the power off operation
func NewPowerOff(ctx *middleware.Context, handler PowerOffHandler) *PowerOff {
	return &PowerOff{Context: ctx, Handler: handler}
}

/*PowerOff swagger:route GET /{speakerName}/powerOff key powerOff

powers off a device

*/
type PowerOff struct {
	Context *middleware.Context
	Handler PowerOffHandler
}

func (o *PowerOff) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPowerOffParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
