// Code generated by go-swagger; DO NOT EDIT.

package key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// PressKeyURL generates an URL for the press key operation
type PressKeyURL struct {
	KeyID       string
	SpeakerName string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PressKeyURL) WithBasePath(bp string) *PressKeyURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PressKeyURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *PressKeyURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/{speakerName}/key/{keyId}"

	keyID := o.KeyID
	if keyID != "" {
		_path = strings.Replace(_path, "{keyId}", keyID, -1)
	} else {
		return nil, errors.New("keyId is required on PressKeyURL")
	}

	speakerName := o.SpeakerName
	if speakerName != "" {
		_path = strings.Replace(_path, "{speakerName}", speakerName, -1)
	} else {
		return nil, errors.New("speakerName is required on PressKeyURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *PressKeyURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *PressKeyURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *PressKeyURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on PressKeyURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on PressKeyURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *PressKeyURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
