// Code generated by go-swagger; DO NOT EDIT.

package key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/theovassiliou/soundtouch-golang/server/models"
)

// PressKeyNoContentCode is the HTTP code returned for type PressKeyNoContent
const PressKeyNoContentCode int = 204

/*PressKeyNoContent empty on success

swagger:response pressKeyNoContent
*/
type PressKeyNoContent struct {
}

// NewPressKeyNoContent creates PressKeyNoContent with default headers values
func NewPressKeyNoContent() *PressKeyNoContent {

	return &PressKeyNoContent{}
}

// WriteResponse to the client
func (o *PressKeyNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*PressKeyDefault generic error response

swagger:response pressKeyDefault
*/
type PressKeyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPressKeyDefault creates PressKeyDefault with default headers values
func NewPressKeyDefault(code int) *PressKeyDefault {
	if code <= 0 {
		code = 500
	}

	return &PressKeyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the press key default response
func (o *PressKeyDefault) WithStatusCode(code int) *PressKeyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the press key default response
func (o *PressKeyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the press key default response
func (o *PressKeyDefault) WithPayload(payload *models.Error) *PressKeyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the press key default response
func (o *PressKeyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PressKeyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
