// Code generated by go-swagger; DO NOT EDIT.

package key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PresetsHandlerFunc turns a function with the right signature into a presets handler
type PresetsHandlerFunc func(PresetsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PresetsHandlerFunc) Handle(params PresetsParams) middleware.Responder {
	return fn(params)
}

// PresetsHandler interface for that can handle valid presets params
type PresetsHandler interface {
	Handle(PresetsParams) middleware.Responder
}

// NewPresets creates a new http.Handler for the presets operation
func NewPresets(ctx *middleware.Context, handler PresetsHandler) *Presets {
	return &Presets{Context: ctx, Handler: handler}
}

/*Presets swagger:route GET /{speakerName}/presets key device presets

This method will return all 6 presets that are configured on the SoundTouch device.

*/
type Presets struct {
	Context *middleware.Context
	Handler PresetsHandler
}

func (o *Presets) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPresetsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
