// Code generated by go-swagger; DO NOT EDIT.

package key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewPresetsParams creates a new PresetsParams object
// no default values defined in spec.
func NewPresetsParams() PresetsParams {

	return PresetsParams{}
}

// PresetsParams contains all the bound params for the presets operation
// typically these are obtained from a http.Request
//
// swagger:parameters presets
type PresetsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The name of device
	  Required: true
	  In: path
	*/
	SpeakerName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPresetsParams() beforehand.
func (o *PresetsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rSpeakerName, rhkSpeakerName, _ := route.Params.GetOK("speakerName")
	if err := o.bindSpeakerName(rSpeakerName, rhkSpeakerName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSpeakerName binds and validates parameter SpeakerName from path.
func (o *PresetsParams) bindSpeakerName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.SpeakerName = raw

	return nil
}
