// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListHandlerFunc turns a function with the right signature into a list handler
type ListHandlerFunc func(ListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListHandlerFunc) Handle(params ListParams) middleware.Responder {
	return fn(params)
}

// ListHandler interface for that can handle valid list params
type ListHandler interface {
	Handle(ListParams) middleware.Responder
}

// NewList creates a new http.Handler for the list operation
func NewList(ctx *middleware.Context, handler ListHandler) *List {
	return &List{Context: ctx, Handler: handler}
}

/*List swagger:route GET /device/list device list

This url will return a JSON object with the found soundtouch devices on your network. When unplugging one of your soundtouches, the device will not be in the list when making a new requests. Even the soundtouches that are powered off are returned. Per soundtouch, only the basic information is displayed.

*/
type List struct {
	Context *middleware.Context
	Handler ListHandler
}

func (o *List) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
