// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Soundtouch RESTful/json server
//
//  This applications implements a RESTful/json based API for the soundtouch system.
//  It's implemented as an API which is described by this swagger spec document.
//
//  The server discovers automatically all Soundtouch devices present in the LAN.
//  It's intend is to ease the communication with Boses Soundtouch system.
//
//  Schemes:
//    http
//  Host: localhost:5006
//  BasePath: /
//  Version: 0.0.1
//
//  Consumes:
//    - application/berlin.vassiliou-pohl.soundtouch-golang.v1+json
//
//  Produces:
//    - application/berlin.vassiliou-pohl.soundtouch-golang.v1+json
//
// swagger:meta
package restapi
